# Generated by Django 4.1.7 on 2023-05-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commment_count',
            field=models.IntegerField(default=0),
        ),
    ]
