# Generated by Django 4.1.7 on 2023-05-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_commment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commment_count',
            new_name='comment_count',
        ),
    ]
