# Generated by Django 4.1.7 on 2023-03-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0004_alter_contact_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
