# Generated by Django 4.1.7 on 2023-03-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0005_alter_contact_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
