# Generated by Django 4.1.7 on 2023-03-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0007_cheap_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheap_package',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
