# Generated by Django 4.1.7 on 2023-03-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0011_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coounted_viwes',
            new_name='counted_viwes',
        ),
    ]
