# Generated by Django 4.1.7 on 2023-04-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0016_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={},
        ),
    ]
