# Generated by Django 4.1.7 on 2023-04-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0017_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
