# Generated by Django 4.1.7 on 2023-04-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0018_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
