# Generated by Django 4.1.7 on 2023-04-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0019_alter_contact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(),
        ),
    ]
