# Generated by Django 4.1.7 on 2023-04-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_weblog', '0020_alter_contact_name_alter_contact_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='subject', max_length=255),
        ),
    ]
